### ISSUE TITLE
Object 'outcomes.of.interest' not found

### ISSUE THREAD

**Issue by kmkostka** [oxford-pharmacoepi/CovCoagBackgroundIncidence#1]
I used the test.run<-TRUE statement and got this error:
````
Error in eval(ei, envir) : object 'outcomes.of.interest' not found
````

**Comment by kmkostka** [comment]
If I run test.run <- FALSE, I get a different error:

````
Error in lapply(list(...), function(x) { : 
  object 'cohortTableOutcomes' not found
 ````

**edit:** I self-soothed. This was because I forgot to load in your parameter. Doh.

**Comment by kmkostka** [comment]
New error when using test.run <- FALSE:

Connecting using Redshift driver
[1] "Create empty cohort table"
  |===============================================================================================| 100%
Executing SQL took 2.03 secs
[1] "- Getting outcome: [EB] CovCoag Cardiac arrhythmia hospitalised (1 of 44)"
  |===========================                                                                    |  28%Error: 

````
Error: 
Error executing SQL:
java.sql.SQLException: [Amazon](500310) Invalid operation: relation "study_reference.cohort_inclusion_result" does not exist;
````

````
DBMS:
redshift

Error:
java.sql.SQLException: [Amazon](500310) Invalid operation: relation "study_reference.cohort_inclusion_result" does not exist;

SQL:
delete from study_reference.cohort_inclusion_result where cohort_definition_id = 573 and mode_id = 0

R version:
R version 4.0.3 (2020-10-10)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- epiR (2.0.19)
- survival (3.1-12)
- forcats (0.5.0)
- scales (1.1.1)
- tableone (0.11.1)
- rmarkdown (2.1)
- RSQLite (2.2.1)
- kableExtra (1.1.0)
- tidyr (1.1.2)
- dbplyr (2.0.0)
- DBI (1.1.1)
- ggplot2 (3.3.2)
- stringr (1.4.0)
- lubridate (1.7.9)
- here (0.1)
- FeatureExtraction (3.1.0)
- Andromeda (0.4.0)
- dplyr (1.0.2)
- DatabaseConnector (4.0.0)
- SqlRender (1.7.0)
````

**Comment by hms1** [comment]
```
Error: 
Error executing SQL:
java.sql.SQLException: [Amazon](500310) Invalid operation: relation "study_reference.cohort_inclusion_result" does not exist;
```
The current cohort definition .sql files are those that write inclusion rule attrition statistics to the database. Unless these tables are created beforehand or already exists in `results_database_schema`, cohort execution will fail as above.

It doesn't look like the inclusion stats are used elsewhere in the study and so the cohort definition sql that does not write inclusion stats should be used. As a temporary workaround, I added a line to `RunAnalyasis.R` that removes the part of the sql that writes the inclusion rule stats before executing. Between current lines 151 and 152:

```r
  sql <- sub("BEGIN: Inclusion Impact Analysis - event.*END: Inclusion Impact Analysis - person", "", sql)
```

After that, the study runs for me without further issue.

**Comment by edward-burn** [comment]
All the above now should be fixed in the latest release
