### ISSUE TITLE
DBI package

### ISSUE THREAD

**Issue by PRijnbeek** [oxford-pharmacoepi/CovCoagBackgroundIncidence#3]
I do not really understand why you are using the DBI package and library(RPostgreSQL).

Can you explain? This will create issues with data partners.

db <- dbConnect("....") 
(also note that comments should be above the line they are about)

please add more information in the readme itself, it takes time for everyone to figure this out since it is not following OHDSI conventions.

**Comment by edward-burn** [comment]
Using dbConnect allowed me to make use of the dbplyr (https://dbplyr.tidyverse.org/index.html) package, which allows one to use the tidyverse style R code that I´m most familiar with. Integration with dplyr is an open issue for Database Connector (https://github.com/OHDSI/DatabaseConnector/issues/35), but I don´t think this is yet resolved. Appreciate this could well be a pain point for data partners, but I think this is all sites for this study now have been able to set this up. I´ve added a link to the readme which has database specific information for creating the required connection
